title: NativeDev Documentation
description: Native Linux Development Environment Manager
remote_theme: just-the-docs/just-the-docs

url: https://sayedsahin.github.io
baseurl: /nativedev

search_enabled: true

aux_links:
  GitHub Repository:
    - https://github.com/sayedsahin/nativedev
